REE_VALENCY = 3
REE_OXIDE_STOICHIOMETRIC_PROPORTION = 2

DYSPROSIUM = {
    "NAME": "Disprósio",
    "SYMBOL": "Dy",
    "ATOMIC_WEIGHT": 162.5, # g/mol
    "OXIDE_WEIGHT": 372.998, # g/mol
    "VALENCY": REE_VALENCY,
    "OXIDE_STOICHIOMETRIC_PROPORTION": REE_OXIDE_STOICHIOMETRIC_PROPORTION
}

HOLMIUM = {
    "NAME": "Hólmio",
    "SYMBOL": "Ho",
    "ATOMIC_WEIGHT": 164.93032, # g/mol
    "OXIDE_WEIGHT": 377.858, # g/mol
    "VALENCY": REE_VALENCY,
    "OXIDE_STOICHIOMETRIC_PROPORTION": REE_OXIDE_STOICHIOMETRIC_PROPORTION
}