TIME_REFERENCE = 1 # year
TOTAL_PRODUCTION = 100 # ton

STRIPPING_SOLUTION_ACID_CONCENTRATION = 3 # mol/L
HEAD_LOSS_BETWEEN_CELLS = 0.1 # m

# Costs
ENERGY_COST_PER_KWH = 0.1 # $/kWh
OPERATORS_COST = 1 # $/operator

# Equilibrium
REE_SX_EQUILIBRIUM_TIME = 15 # min
PHASE_SETTLING_TIME = 10 # min

# Constants
ACCELERATION_OF_GRAVITY = 9.81 # m/s²

# Distances of Equipment
DISTANCE_BETWEEN_ORG_TANK_AND_RAFFINATE_CELL = 1
DISTANCE_BETWEEN_AQ_TANK_AND_FEED_CELL = 1
DISTANCE_BETWEEN_CELLS = 1